[mu2e_trk_boxes]
trk-01
trk-02
trk-03
trk-04
trk-05
trk-06
trk-07
trk-08
trk-09
trk-10
trk-11
trk-12
trk-13
trk-14
trk-15
trk-16
trk-17

# Intended remote task sequence:
# /home/mu2ehwdev/program_all_FPGA_AL9.sh /home/mu2ehwdev/DTC_Firmware/DTC2026Jan16_17_22.1_6ROC/DTC.bit
[all:vars]
ansible_python_interpreter=/usr/bin/python3
